services:
  - type: web
    name: golis
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
